# This template is a starter workflow to get the basics of R, R packages, and optional quarto installed

name: Starter R workflow

# Controls when the workflow will run - using a cronjob in this case
on:
  # Triggers the workflow on a schedule  - this runs at one minute past each hour.
    schedule:
      - cron:  "1, * * * *"
    workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    run-r-script:
      runs-on: ubuntu-latest
      env:
        VERY_SECRET_KEY: ${{ secrets.VERY_SECRET_KEY }}  ##create a secret if you need to use it in the code

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it - makes files accessible to this workflow
        - uses: actions/checkout@v4
      
      #install R
        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: '4.5.0' #can specify the R version you want

        
      #install dependencies in the "description" file 
        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            cache-version: 1

    # option to install quarto and a quarto render step   
   
    # - uses: quarto-dev/quarto-actions/setup@v2
    #   with:
    #     version: 1.4.515 #set version here

    # - uses: quarto-dev/quarto-actions/render@v2
    #   with:
    #     to: html

        - name: Run the R script
          run: |
            Rscript "my_script.R"

    # - name: Commit Data
    #   run: |
    #     git config --local user.email "actions@github.com"
    #     git config --local user.name "GitHub Actions"
    #     git add MYFILE.html
    #     git commit -m "MY MESSAGE" || echo "No changes to commit"
    #     git push origin || echo "No changes to commit"-








  
